In [9]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib as plt
df = pd.read_csv("crime_data.csv")

In [10]:
df.corr()

          X1        X2        X3        X4        X5        X6        X7
X1  1.000000  0.756505  0.533198 -0.135459  0.322519 -0.175224 -0.026283
X2  0.756505  1.000000  0.509339 -0.184445  0.291031 -0.199070 -0.045570
X3  0.533198  0.509339  1.000000  0.120265  0.311526 -0.277475  0.124502
X4 -0.135459 -0.184445  0.120265  1.000000 -0.537162  0.182364  0.681072
X5  0.322519  0.291031  0.311526 -0.537162  1.000000 -0.626953 -0.513958
X6 -0.175224 -0.199070 -0.277475  0.182364 -0.626953  1.000000  0.591663
X7 -0.026283 -0.045570  0.124502  0.681072 -0.513958  0.591663  1.000000